/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.cscd.webservice;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.1.12 2017-09-14T15:48:20.165+08:00 Generated source
 * version: 3.1.12
 */
@WebFault(name = "CscdServiceException", targetNamespace = "http://webservice.cscd.com")
public class CscdServiceException_Exception extends java.lang.Exception {

    private CscdServiceException cscdServiceException;

    public CscdServiceException_Exception() {
        super();
    }

    public CscdServiceException_Exception(String message) {
        super(message);
    }

    public CscdServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CscdServiceException_Exception(String message, CscdServiceException cscdServiceException) {
        super(message);
        this.cscdServiceException = cscdServiceException;
    }

    public CscdServiceException_Exception(
                                          String message, CscdServiceException cscdServiceException, Throwable cause) {
        super(message, cause);
        this.cscdServiceException = cscdServiceException;
    }

    public CscdServiceException getFaultInfo() {
        return this.cscdServiceException;
    }
}
